### ISSUE TITLE
ePPing reference

### ISSUE THREAD

**Issue by yskim29** [sco-edge/croffset#4]
If you have an ePPing reference, I'd appreciate it if you could share it.

**Comment by sunjaek** [comment]
Simon Sundberg, Anna Brunstrom, Simone Ferlin-Reiter, Toke Høiland-Jørgensen, and Jesper Dangaard Brouer, "Efficient Continuous Latency Monitoring with eBPF," in Proc. of Passive_ and Active Measurement Conference, March 2023.
